--11.tbltestbookreg.sql
--시험지 더미데이터

insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-10-01','yyyy-mm-dd'),'등록',1,11);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-10-01','yyyy-mm-dd'),'등록',1,30);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-10-01','yyyy-mm-dd'),'등록',1,19);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-10-01','yyyy-mm-dd'),'등록',1,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-10-01','yyyy-mm-dd'),'등록',1,3);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-23','yyyy-mm-dd'),'등록',2,17);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-23','yyyy-mm-dd'),'등록',2,2);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-23','yyyy-mm-dd'),'등록',2,6);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-23','yyyy-mm-dd'),'등록',2,5);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-23','yyyy-mm-dd'),'등록',2,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-12','yyyy-mm-dd'),'등록',3,18);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-12','yyyy-mm-dd'),'등록',3,5);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-12','yyyy-mm-dd'),'등록',3,30);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-12','yyyy-mm-dd'),'등록',3,15);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-12','yyyy-mm-dd'),'등록',3,28);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-04','yyyy-mm-dd'),'등록',4,13);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-04','yyyy-mm-dd'),'등록',4,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-04','yyyy-mm-dd'),'등록',4,29);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-04','yyyy-mm-dd'),'등록',4,15);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-04','yyyy-mm-dd'),'등록',4,1);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-05','yyyy-mm-dd'),'등록',5,29);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-05','yyyy-mm-dd'),'등록',5,14);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-05','yyyy-mm-dd'),'등록',5,22);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-05','yyyy-mm-dd'),'등록',5,16);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-05','yyyy-mm-dd'),'등록',5,28);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-20','yyyy-mm-dd'),'등록',6,1);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-20','yyyy-mm-dd'),'등록',6,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-20','yyyy-mm-dd'),'등록',6,27);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-20','yyyy-mm-dd'),'등록',6,26);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-20','yyyy-mm-dd'),'등록',6,30);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-12','yyyy-mm-dd'),'등록',7,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-12','yyyy-mm-dd'),'등록',7,15);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-12','yyyy-mm-dd'),'등록',7,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-12','yyyy-mm-dd'),'등록',7,28);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-12','yyyy-mm-dd'),'등록',7,7);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-04','yyyy-mm-dd'),'등록',8,4);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-04','yyyy-mm-dd'),'등록',8,24);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-04','yyyy-mm-dd'),'등록',8,7);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-04','yyyy-mm-dd'),'등록',8,29);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-04','yyyy-mm-dd'),'등록',8,17);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-01','yyyy-mm-dd'),'등록',9,7);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-01','yyyy-mm-dd'),'등록',9,3);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-01','yyyy-mm-dd'),'등록',9,8);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-01','yyyy-mm-dd'),'등록',9,5);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-01','yyyy-mm-dd'),'등록',9,13);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-17','yyyy-mm-dd'),'등록',10,21);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-17','yyyy-mm-dd'),'등록',10,20);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-17','yyyy-mm-dd'),'등록',10,28);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-17','yyyy-mm-dd'),'등록',10,24);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-17','yyyy-mm-dd'),'등록',10,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-11','yyyy-mm-dd'),'등록',11,13);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-11','yyyy-mm-dd'),'등록',11,18);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-11','yyyy-mm-dd'),'등록',11,7);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-11','yyyy-mm-dd'),'등록',11,4);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-11','yyyy-mm-dd'),'등록',11,21);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-26','yyyy-mm-dd'),'등록',12,3);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-26','yyyy-mm-dd'),'등록',12,5);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-26','yyyy-mm-dd'),'등록',12,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-26','yyyy-mm-dd'),'등록',12,26);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-26','yyyy-mm-dd'),'등록',12,15);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-04','yyyy-mm-dd'),'등록',13,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-04','yyyy-mm-dd'),'등록',13,23);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-04','yyyy-mm-dd'),'등록',13,1);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-04','yyyy-mm-dd'),'등록',13,9);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-03-04','yyyy-mm-dd'),'등록',13,18);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-15','yyyy-mm-dd'),'등록',14,30);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-15','yyyy-mm-dd'),'등록',14,14);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-15','yyyy-mm-dd'),'등록',14,29);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-15','yyyy-mm-dd'),'등록',14,28);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-15','yyyy-mm-dd'),'등록',14,15);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-29','yyyy-mm-dd'),'등록',15,11);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-29','yyyy-mm-dd'),'등록',15,7);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-29','yyyy-mm-dd'),'등록',15,20);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-29','yyyy-mm-dd'),'등록',15,28);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-29','yyyy-mm-dd'),'등록',15,22);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-19','yyyy-mm-dd'),'등록',16,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-19','yyyy-mm-dd'),'등록',16,6);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-19','yyyy-mm-dd'),'등록',16,8);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-19','yyyy-mm-dd'),'등록',16,20);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-19','yyyy-mm-dd'),'등록',16,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-24','yyyy-mm-dd'),'등록',17,20);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-24','yyyy-mm-dd'),'등록',17,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-24','yyyy-mm-dd'),'등록',17,25);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-24','yyyy-mm-dd'),'등록',17,21);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-24','yyyy-mm-dd'),'등록',17,27);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-16','yyyy-mm-dd'),'등록',18,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-16','yyyy-mm-dd'),'등록',18,24);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-16','yyyy-mm-dd'),'등록',18,6);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-16','yyyy-mm-dd'),'등록',18,11);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-16','yyyy-mm-dd'),'등록',18,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-14','yyyy-mm-dd'),'등록',19,15);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-14','yyyy-mm-dd'),'등록',19,22);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-14','yyyy-mm-dd'),'등록',19,24);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-14','yyyy-mm-dd'),'등록',19,2);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-07-14','yyyy-mm-dd'),'등록',19,20);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-07','yyyy-mm-dd'),'등록',20,7);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-07','yyyy-mm-dd'),'등록',20,6);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-07','yyyy-mm-dd'),'등록',20,15);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-07','yyyy-mm-dd'),'등록',20,5);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-09-07','yyyy-mm-dd'),'등록',20,21);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-19','yyyy-mm-dd'),'등록',21,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-19','yyyy-mm-dd'),'등록',21,7);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-19','yyyy-mm-dd'),'등록',21,10);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-19','yyyy-mm-dd'),'등록',21,2);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-19','yyyy-mm-dd'),'등록',21,4);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-26','yyyy-mm-dd'),'등록',22,9);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-26','yyyy-mm-dd'),'등록',22,4);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-26','yyyy-mm-dd'),'등록',22,29);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-26','yyyy-mm-dd'),'등록',22,18);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-26','yyyy-mm-dd'),'등록',22,17);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-26','yyyy-mm-dd'),'등록',23,16);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-26','yyyy-mm-dd'),'등록',23,20);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-26','yyyy-mm-dd'),'등록',23,5);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-26','yyyy-mm-dd'),'등록',23,21);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-02-26','yyyy-mm-dd'),'등록',23,17);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-09','yyyy-mm-dd'),'등록',24,13);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-09','yyyy-mm-dd'),'등록',24,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-09','yyyy-mm-dd'),'등록',24,23);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-09','yyyy-mm-dd'),'등록',24,19);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-06-09','yyyy-mm-dd'),'등록',24,30);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-11-27','yyyy-mm-dd'),'등록',25,26);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-11-27','yyyy-mm-dd'),'등록',25,4);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-11-27','yyyy-mm-dd'),'등록',25,6);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-11-27','yyyy-mm-dd'),'등록',25,25);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-11-27','yyyy-mm-dd'),'등록',25,22);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-01-09','yyyy-mm-dd'),'등록',26,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-01-09','yyyy-mm-dd'),'등록',26,25);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-01-09','yyyy-mm-dd'),'등록',26,19);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-01-09','yyyy-mm-dd'),'등록',26,8);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-01-09','yyyy-mm-dd'),'등록',26,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-29','yyyy-mm-dd'),'등록',27,8);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-29','yyyy-mm-dd'),'등록',27,6);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-29','yyyy-mm-dd'),'등록',27,16);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-29','yyyy-mm-dd'),'등록',27,19);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-04-29','yyyy-mm-dd'),'등록',27,18);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-31','yyyy-mm-dd'),'등록',28,27);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-31','yyyy-mm-dd'),'등록',28,15);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-31','yyyy-mm-dd'),'등록',28,7);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-31','yyyy-mm-dd'),'등록',28,27);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-12-31','yyyy-mm-dd'),'등록',28,5);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-31','yyyy-mm-dd'),'등록',29,24);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-31','yyyy-mm-dd'),'등록',29,14);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-31','yyyy-mm-dd'),'등록',29,30);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-31','yyyy-mm-dd'),'등록',29,28);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-05-31','yyyy-mm-dd'),'등록',29,7);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-19','yyyy-mm-dd'),'등록',30,4);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-19','yyyy-mm-dd'),'등록',30,17);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-19','yyyy-mm-dd'),'등록',30,12);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-19','yyyy-mm-dd'),'등록',30,27);
insert into tblTestBookReg (testBook_seq,testBook_reg_date,testBook_reg_check,test_seq,testQuestion_seq) values (seqTestBookReg.nextval,to_date('2020-08-19','yyyy-mm-dd'),'등록',30,13);

update tblTestBookReg
set testBook_reg_date = null, testBook_reg_check = '미등록'
where test_seq = 30;

update tblTestBookReg
set testBook_reg_check = '미등록', testBook_reg_date = null
where test_seq = 25;


update tblTestBookReg
set testBook_reg_check = '미등록', testBook_reg_date = null
where test_seq = 15;
